language: node_js
node_js:
  - 16

service: 
  - docker

# Pre-testing installs
install: 
  - echo ""nothing needs to be installed

# Script to be run such as tests
before_script:
  - echo "no tests"

script: 
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed laclac0901/udagram-api-feed:v4a
  - docker tag udagram-api-user laclac0901/udagram-api-user:v4a
  - docker tag udagram-frontend laclac0901/udagram-frontend:local
  - docker tag reverseproxy laclac0901/reverseproxy:v4a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push laclac0901/udagram-api-feed:v4a
  - docker push laclac0901/udagram-api-user:v4a
  - docker push laclac0901/udagram-frontend:local
  - docker push laclac0901/reverseproxy:v4a

  